// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwewwjdxncjzyrzmjygv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3ZXd3amR4bmNqenlyem1qeWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0Nzk1OTcsImV4cCI6MjA1MjA1NTU5N30.BWn2d2wgoL1O5h35y3ciYWj5J2xd0fEFz_YHWQf1tsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);